---
title: "p8105_hw6_sl4658"
author: "Simin Ling"
date: "12/3/2020"
output: github_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)
```


## Problem 1
Create a city_state variable and a binary variable indicating whether the homicide is solved.
```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv", na = c("", "NA", "Unknown")) %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    victim_race = as.factor(victim_race),
    victim_sex = as.factor(victim_sex),
    resolved = case_when(
      disposition  == "Closed without arrest" ~ 0,
      disposition  == "Open/No arrest" ~ 0,
      disposition  == "Closed by arrest" ~ 1)
  ) %>% 
  filter(
    city_state != "Tulsa, AL",
    victim_race %in% c("White", "Black")
    ) %>% 
  select(city_state, resolved, victim_age, victim_race, victim_sex)
```


Create a dataframe for Baltimore, MD
```{r}
baltimore_df = 
  homicide_df %>%
  filter(city_state == "Baltimore, MD")

head(baltimore_df)
```


Fit the logistic regression for Baltimore, MD
```{r}
glm(resolved ~ victim_age + victim_race + victim_sex, 
    data = baltimore_df,
    family = binomial()) %>%
  broom::tidy() %>%
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>%
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```


Run glm for each of the cities in dataset
```{r}
models_results_df = 
  homicide_df %>%
  nest(data = -city_state) %>% 
  mutate(
    models = 
      map(.x = data, ~glm(resolved ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())), 
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state, results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI"))
```


Create a plot that shows the estimated ORs and CIs for each city. 
```{r}
models_results_df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

As shown in the plot, the estimated OR of solving homicides comparing for 
